### ISSUE TITLE
af9033: I2C read failed reg:0045

### ISSUE THREAD

**Issue by roondar** [xgazza/DVB-AF9035_kernel-3.2.0#2]
uname -a
Linux roondar-server 3.2.13-1-ARCH #1 SMP PREEMPT Sat Mar 24 09:10:39 CET 2012 x86_64 Intel(R) Atom(TM) CPU D525 @ 1.80GHz GenuineIntel GNU/Linux

I've some "af9033: I2C read failed reg:0045" messages and then i have to unplug  my usb device.
I tried to put "options dvb-core dvb_powerdown_on_sleep=0" in /etc/modprobe.d/options.conf but it doesn't works.
It's normal ?

**Comment by xgazza** [comment]
Is a bug of  "not RC" devices...

IR polling stop the powerdown procedure (cause I2C read errors)

the HD "green" model is immune; HD and HD PRO : no

Patch comin soon...

**Comment by roondar** [comment]
I have the HD "green" model !

**Comment by ivanohe** [comment]
Hello,
Is there a patch for this bug ?
