### ISSUE TITLE
Add support for additional model

### ISSUE THREAD

**Issue by ghost** [xgazza/DVB-AF9035_kernel-3.2.0#3]
Hello,
First of all, I must say I'm rather new to those areas, so please bear with me...
It didn't take me long to realize that my AF9035 based WandTV USB DVB-T stick is poorly supported under Ubuntu 12.04, and in fact I couldn't get it to work at all.
This seem to be the closest think to a working driver for this device under kernel 3.2.0, and I was wondering If you could add support for my device (ID 15a4:1001).
Thanks, Adam.

**Comment by xgazza** [comment]
My driver is obsolete...
Install media_build for new driver (by Antti Palosaari): http://git.linuxtv.
org/media_build.git

Device ID 15a4:1001 is supported ;-)

**Comment by ghost** [comment]
Thank you very much for the reference, it works great!
